server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: appointment-platform

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:mykare_appointments}
    username: ${POSTGRES_USER:mykare}
    password: ${POSTGRES_PASSWORD:mykare_password}

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    appointment-events-topic: ${APPOINTMENT_EVENTS_TOPIC:appointment-events}
  jwt:
    secret: ${JWT_SECRET:ARj4ptWyFeD26g9nQ8fjeTjLRKjjTcRxzstEfgC6cy8}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:1440}